# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userRelationships.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "GrpcAgentPlatform.Agent" do
    optional :id, :int64, 1
    optional :name, :string, 2
  end
  add_message "GrpcAgentPlatform.Customer" do
    optional :id, :int64, 1
    optional :name, :string, 2
    optional :avaterUrl, :string, 3
  end
  add_message "GrpcAgentPlatform.UserRelationsCustomer" do
    repeated :agents, :message, 1, "GrpcAgentPlatform.Agent"
    repeated :travelArrengers, :message, 2, "GrpcAgentPlatform.Customer"
    repeated :customers, :message, 3, "GrpcAgentPlatform.Customer"
  end
  add_message "GrpcAgentPlatform.UserRelationsAgent" do
    repeated :customers, :message, 1, "GrpcAgentPlatform.Customer"
    repeated :colleagues, :message, 2, "GrpcAgentPlatform.Agent"
  end
  add_message "GrpcAgentPlatform.User" do
    optional :id, :int64, 1
    optional :tenant, :string, 2
  end
end

module GrpcAgentPlatform
  Agent = Google::Protobuf::DescriptorPool.generated_pool.lookup("GrpcAgentPlatform.Agent").msgclass
  Customer = Google::Protobuf::DescriptorPool.generated_pool.lookup("GrpcAgentPlatform.Customer").msgclass
  UserRelationsCustomer = Google::Protobuf::DescriptorPool.generated_pool.lookup("GrpcAgentPlatform.UserRelationsCustomer").msgclass
  UserRelationsAgent = Google::Protobuf::DescriptorPool.generated_pool.lookup("GrpcAgentPlatform.UserRelationsAgent").msgclass
  User = Google::Protobuf::DescriptorPool.generated_pool.lookup("GrpcAgentPlatform.User").msgclass
end
