# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: userRelationships.proto for package 'GrpcAgentPlatform'

require 'grpc'
require 'userRelationships_pb'

module GrpcAgentPlatform
  module UserRelationships
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'GrpcAgentPlatform.UserRelationships'

      rpc :RetrieveCustomerRelations, User, UserRelationsCustomer
      rpc :RetrieveAgentRelations, User, UserRelationsAgent
    end

    Stub = Service.rpc_stub_class
  end
end
