# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model/user.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Model.User" do
    optional :id, :int64, 1
    optional :name, :string, 2
    optional :tenant, :string, 3
    optional :isCustomer, :string, 4
    optional :avatarURL, :string, 5
  end
end

module Model
  User = Google::Protobuf::DescriptorPool.generated_pool.lookup("Model.User").msgclass
end
