# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat-backend/chat.proto

require 'google/protobuf'

require 'Model/user_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "ChatService.Message" do
    optional :id, :int64, 1
    optional :timestamp, :string, 2
    optional :tenant, :string, 3
    optional :roomId, :string, 4
    optional :text, :string, 5
    optional :senderId, :string, 6
    optional :senderName, :string, 7
  end
  add_message "ChatService.MessageList" do
    repeated :messages, :message, 1, "ChatService.Message"
  end
  add_message "ChatService.SendMessageResponse" do
    optional :sent, :bool, 1
  end
  add_message "ChatService.Room" do
    optional :tenant, :string, 1
    optional :id, :string, 2
    optional :lastSeenMessageTimestamp, :string, 3
  end
  add_message "ChatService.Channel" do
    optional :id, :int64, 1
    optional :channelUniqueId, :string, 2
    optional :channelType, :string, 3
    optional :channelTitle, :string, 4
    optional :tenant, :string, 5
    repeated :users, :message, 6, "Model.User"
  end
  add_message "ChatService.ChannelList" do
    repeated :channels, :message, 1, "ChatService.Channel"
  end
  add_message "ChatService.Empty" do
  end
  add_message "ChatService.AccessToken" do
    optional :token, :string, 1
  end
end

module ChatService
  Message = Google::Protobuf::DescriptorPool.generated_pool.lookup("ChatService.Message").msgclass
  MessageList = Google::Protobuf::DescriptorPool.generated_pool.lookup("ChatService.MessageList").msgclass
  SendMessageResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("ChatService.SendMessageResponse").msgclass
  Room = Google::Protobuf::DescriptorPool.generated_pool.lookup("ChatService.Room").msgclass
  Channel = Google::Protobuf::DescriptorPool.generated_pool.lookup("ChatService.Channel").msgclass
  ChannelList = Google::Protobuf::DescriptorPool.generated_pool.lookup("ChatService.ChannelList").msgclass
  Empty = Google::Protobuf::DescriptorPool.generated_pool.lookup("ChatService.Empty").msgclass
  AccessToken = Google::Protobuf::DescriptorPool.generated_pool.lookup("ChatService.AccessToken").msgclass
end
