/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.GrpcAgentPlatform.Agent', null, global);
goog.exportSymbol('proto.GrpcAgentPlatform.Customer', null, global);
goog.exportSymbol('proto.GrpcAgentPlatform.User', null, global);
goog.exportSymbol('proto.GrpcAgentPlatform.UserRelationsAgent', null, global);
goog.exportSymbol('proto.GrpcAgentPlatform.UserRelationsCustomer', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GrpcAgentPlatform.Agent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.GrpcAgentPlatform.Agent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.GrpcAgentPlatform.Agent.displayName = 'proto.GrpcAgentPlatform.Agent';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GrpcAgentPlatform.Agent.prototype.toObject = function(opt_includeInstance) {
  return proto.GrpcAgentPlatform.Agent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GrpcAgentPlatform.Agent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GrpcAgentPlatform.Agent.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GrpcAgentPlatform.Agent}
 */
proto.GrpcAgentPlatform.Agent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GrpcAgentPlatform.Agent;
  return proto.GrpcAgentPlatform.Agent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GrpcAgentPlatform.Agent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GrpcAgentPlatform.Agent}
 */
proto.GrpcAgentPlatform.Agent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GrpcAgentPlatform.Agent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GrpcAgentPlatform.Agent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GrpcAgentPlatform.Agent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GrpcAgentPlatform.Agent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.GrpcAgentPlatform.Agent.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.GrpcAgentPlatform.Agent.prototype.setId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.GrpcAgentPlatform.Agent.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.GrpcAgentPlatform.Agent.prototype.setName = function(value) {
  jspb.Message.setField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GrpcAgentPlatform.Customer = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.GrpcAgentPlatform.Customer, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.GrpcAgentPlatform.Customer.displayName = 'proto.GrpcAgentPlatform.Customer';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GrpcAgentPlatform.Customer.prototype.toObject = function(opt_includeInstance) {
  return proto.GrpcAgentPlatform.Customer.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GrpcAgentPlatform.Customer} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GrpcAgentPlatform.Customer.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    avaterurl: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GrpcAgentPlatform.Customer}
 */
proto.GrpcAgentPlatform.Customer.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GrpcAgentPlatform.Customer;
  return proto.GrpcAgentPlatform.Customer.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GrpcAgentPlatform.Customer} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GrpcAgentPlatform.Customer}
 */
proto.GrpcAgentPlatform.Customer.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setAvaterurl(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GrpcAgentPlatform.Customer.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GrpcAgentPlatform.Customer.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GrpcAgentPlatform.Customer} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GrpcAgentPlatform.Customer.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getAvaterurl();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.GrpcAgentPlatform.Customer.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.GrpcAgentPlatform.Customer.prototype.setId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.GrpcAgentPlatform.Customer.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.GrpcAgentPlatform.Customer.prototype.setName = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string avaterUrl = 3;
 * @return {string}
 */
proto.GrpcAgentPlatform.Customer.prototype.getAvaterurl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.GrpcAgentPlatform.Customer.prototype.setAvaterurl = function(value) {
  jspb.Message.setField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GrpcAgentPlatform.UserRelationsCustomer = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.GrpcAgentPlatform.UserRelationsCustomer.repeatedFields_, null);
};
goog.inherits(proto.GrpcAgentPlatform.UserRelationsCustomer, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.GrpcAgentPlatform.UserRelationsCustomer.displayName = 'proto.GrpcAgentPlatform.UserRelationsCustomer';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.GrpcAgentPlatform.UserRelationsCustomer.repeatedFields_ = [1,2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GrpcAgentPlatform.UserRelationsCustomer.prototype.toObject = function(opt_includeInstance) {
  return proto.GrpcAgentPlatform.UserRelationsCustomer.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GrpcAgentPlatform.UserRelationsCustomer} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GrpcAgentPlatform.UserRelationsCustomer.toObject = function(includeInstance, msg) {
  var f, obj = {
    agentsList: jspb.Message.toObjectList(msg.getAgentsList(),
    proto.GrpcAgentPlatform.Agent.toObject, includeInstance),
    travelarrengersList: jspb.Message.toObjectList(msg.getTravelarrengersList(),
    proto.GrpcAgentPlatform.Customer.toObject, includeInstance),
    customersList: jspb.Message.toObjectList(msg.getCustomersList(),
    proto.GrpcAgentPlatform.Customer.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GrpcAgentPlatform.UserRelationsCustomer}
 */
proto.GrpcAgentPlatform.UserRelationsCustomer.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GrpcAgentPlatform.UserRelationsCustomer;
  return proto.GrpcAgentPlatform.UserRelationsCustomer.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GrpcAgentPlatform.UserRelationsCustomer} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GrpcAgentPlatform.UserRelationsCustomer}
 */
proto.GrpcAgentPlatform.UserRelationsCustomer.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.GrpcAgentPlatform.Agent;
      reader.readMessage(value,proto.GrpcAgentPlatform.Agent.deserializeBinaryFromReader);
      msg.addAgents(value);
      break;
    case 2:
      var value = new proto.GrpcAgentPlatform.Customer;
      reader.readMessage(value,proto.GrpcAgentPlatform.Customer.deserializeBinaryFromReader);
      msg.addTravelarrengers(value);
      break;
    case 3:
      var value = new proto.GrpcAgentPlatform.Customer;
      reader.readMessage(value,proto.GrpcAgentPlatform.Customer.deserializeBinaryFromReader);
      msg.addCustomers(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GrpcAgentPlatform.UserRelationsCustomer.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GrpcAgentPlatform.UserRelationsCustomer.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GrpcAgentPlatform.UserRelationsCustomer} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GrpcAgentPlatform.UserRelationsCustomer.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAgentsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.GrpcAgentPlatform.Agent.serializeBinaryToWriter
    );
  }
  f = message.getTravelarrengersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.GrpcAgentPlatform.Customer.serializeBinaryToWriter
    );
  }
  f = message.getCustomersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.GrpcAgentPlatform.Customer.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Agent agents = 1;
 * @return {!Array.<!proto.GrpcAgentPlatform.Agent>}
 */
proto.GrpcAgentPlatform.UserRelationsCustomer.prototype.getAgentsList = function() {
  return /** @type{!Array.<!proto.GrpcAgentPlatform.Agent>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.GrpcAgentPlatform.Agent, 1));
};


/** @param {!Array.<!proto.GrpcAgentPlatform.Agent>} value */
proto.GrpcAgentPlatform.UserRelationsCustomer.prototype.setAgentsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.GrpcAgentPlatform.Agent=} opt_value
 * @param {number=} opt_index
 * @return {!proto.GrpcAgentPlatform.Agent}
 */
proto.GrpcAgentPlatform.UserRelationsCustomer.prototype.addAgents = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.GrpcAgentPlatform.Agent, opt_index);
};


proto.GrpcAgentPlatform.UserRelationsCustomer.prototype.clearAgentsList = function() {
  this.setAgentsList([]);
};


/**
 * repeated Customer travelArrengers = 2;
 * @return {!Array.<!proto.GrpcAgentPlatform.Customer>}
 */
proto.GrpcAgentPlatform.UserRelationsCustomer.prototype.getTravelarrengersList = function() {
  return /** @type{!Array.<!proto.GrpcAgentPlatform.Customer>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.GrpcAgentPlatform.Customer, 2));
};


/** @param {!Array.<!proto.GrpcAgentPlatform.Customer>} value */
proto.GrpcAgentPlatform.UserRelationsCustomer.prototype.setTravelarrengersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.GrpcAgentPlatform.Customer=} opt_value
 * @param {number=} opt_index
 * @return {!proto.GrpcAgentPlatform.Customer}
 */
proto.GrpcAgentPlatform.UserRelationsCustomer.prototype.addTravelarrengers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.GrpcAgentPlatform.Customer, opt_index);
};


proto.GrpcAgentPlatform.UserRelationsCustomer.prototype.clearTravelarrengersList = function() {
  this.setTravelarrengersList([]);
};


/**
 * repeated Customer customers = 3;
 * @return {!Array.<!proto.GrpcAgentPlatform.Customer>}
 */
proto.GrpcAgentPlatform.UserRelationsCustomer.prototype.getCustomersList = function() {
  return /** @type{!Array.<!proto.GrpcAgentPlatform.Customer>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.GrpcAgentPlatform.Customer, 3));
};


/** @param {!Array.<!proto.GrpcAgentPlatform.Customer>} value */
proto.GrpcAgentPlatform.UserRelationsCustomer.prototype.setCustomersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.GrpcAgentPlatform.Customer=} opt_value
 * @param {number=} opt_index
 * @return {!proto.GrpcAgentPlatform.Customer}
 */
proto.GrpcAgentPlatform.UserRelationsCustomer.prototype.addCustomers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.GrpcAgentPlatform.Customer, opt_index);
};


proto.GrpcAgentPlatform.UserRelationsCustomer.prototype.clearCustomersList = function() {
  this.setCustomersList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GrpcAgentPlatform.UserRelationsAgent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.GrpcAgentPlatform.UserRelationsAgent.repeatedFields_, null);
};
goog.inherits(proto.GrpcAgentPlatform.UserRelationsAgent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.GrpcAgentPlatform.UserRelationsAgent.displayName = 'proto.GrpcAgentPlatform.UserRelationsAgent';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.GrpcAgentPlatform.UserRelationsAgent.repeatedFields_ = [1,2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GrpcAgentPlatform.UserRelationsAgent.prototype.toObject = function(opt_includeInstance) {
  return proto.GrpcAgentPlatform.UserRelationsAgent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GrpcAgentPlatform.UserRelationsAgent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GrpcAgentPlatform.UserRelationsAgent.toObject = function(includeInstance, msg) {
  var f, obj = {
    customersList: jspb.Message.toObjectList(msg.getCustomersList(),
    proto.GrpcAgentPlatform.Customer.toObject, includeInstance),
    colleaguesList: jspb.Message.toObjectList(msg.getColleaguesList(),
    proto.GrpcAgentPlatform.Agent.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GrpcAgentPlatform.UserRelationsAgent}
 */
proto.GrpcAgentPlatform.UserRelationsAgent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GrpcAgentPlatform.UserRelationsAgent;
  return proto.GrpcAgentPlatform.UserRelationsAgent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GrpcAgentPlatform.UserRelationsAgent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GrpcAgentPlatform.UserRelationsAgent}
 */
proto.GrpcAgentPlatform.UserRelationsAgent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.GrpcAgentPlatform.Customer;
      reader.readMessage(value,proto.GrpcAgentPlatform.Customer.deserializeBinaryFromReader);
      msg.addCustomers(value);
      break;
    case 2:
      var value = new proto.GrpcAgentPlatform.Agent;
      reader.readMessage(value,proto.GrpcAgentPlatform.Agent.deserializeBinaryFromReader);
      msg.addColleagues(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GrpcAgentPlatform.UserRelationsAgent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GrpcAgentPlatform.UserRelationsAgent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GrpcAgentPlatform.UserRelationsAgent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GrpcAgentPlatform.UserRelationsAgent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCustomersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.GrpcAgentPlatform.Customer.serializeBinaryToWriter
    );
  }
  f = message.getColleaguesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.GrpcAgentPlatform.Agent.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Customer customers = 1;
 * @return {!Array.<!proto.GrpcAgentPlatform.Customer>}
 */
proto.GrpcAgentPlatform.UserRelationsAgent.prototype.getCustomersList = function() {
  return /** @type{!Array.<!proto.GrpcAgentPlatform.Customer>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.GrpcAgentPlatform.Customer, 1));
};


/** @param {!Array.<!proto.GrpcAgentPlatform.Customer>} value */
proto.GrpcAgentPlatform.UserRelationsAgent.prototype.setCustomersList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.GrpcAgentPlatform.Customer=} opt_value
 * @param {number=} opt_index
 * @return {!proto.GrpcAgentPlatform.Customer}
 */
proto.GrpcAgentPlatform.UserRelationsAgent.prototype.addCustomers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.GrpcAgentPlatform.Customer, opt_index);
};


proto.GrpcAgentPlatform.UserRelationsAgent.prototype.clearCustomersList = function() {
  this.setCustomersList([]);
};


/**
 * repeated Agent colleagues = 2;
 * @return {!Array.<!proto.GrpcAgentPlatform.Agent>}
 */
proto.GrpcAgentPlatform.UserRelationsAgent.prototype.getColleaguesList = function() {
  return /** @type{!Array.<!proto.GrpcAgentPlatform.Agent>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.GrpcAgentPlatform.Agent, 2));
};


/** @param {!Array.<!proto.GrpcAgentPlatform.Agent>} value */
proto.GrpcAgentPlatform.UserRelationsAgent.prototype.setColleaguesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.GrpcAgentPlatform.Agent=} opt_value
 * @param {number=} opt_index
 * @return {!proto.GrpcAgentPlatform.Agent}
 */
proto.GrpcAgentPlatform.UserRelationsAgent.prototype.addColleagues = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.GrpcAgentPlatform.Agent, opt_index);
};


proto.GrpcAgentPlatform.UserRelationsAgent.prototype.clearColleaguesList = function() {
  this.setColleaguesList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GrpcAgentPlatform.User = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.GrpcAgentPlatform.User, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.GrpcAgentPlatform.User.displayName = 'proto.GrpcAgentPlatform.User';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GrpcAgentPlatform.User.prototype.toObject = function(opt_includeInstance) {
  return proto.GrpcAgentPlatform.User.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GrpcAgentPlatform.User} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GrpcAgentPlatform.User.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    tenant: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GrpcAgentPlatform.User}
 */
proto.GrpcAgentPlatform.User.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GrpcAgentPlatform.User;
  return proto.GrpcAgentPlatform.User.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GrpcAgentPlatform.User} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GrpcAgentPlatform.User}
 */
proto.GrpcAgentPlatform.User.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTenant(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GrpcAgentPlatform.User.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GrpcAgentPlatform.User.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GrpcAgentPlatform.User} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GrpcAgentPlatform.User.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getTenant();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.GrpcAgentPlatform.User.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.GrpcAgentPlatform.User.prototype.setId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string tenant = 2;
 * @return {string}
 */
proto.GrpcAgentPlatform.User.prototype.getTenant = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.GrpcAgentPlatform.User.prototype.setTenant = function(value) {
  jspb.Message.setField(this, 2, value);
};


goog.object.extend(exports, proto.GrpcAgentPlatform);
