# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: authentication.proto for package 'GrpcClientAuthentication'

require 'grpc'
require 'authentication_pb'

module GrpcClientAuthentication
  module Chat
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'GrpcClientAuthentication.Chat'

      rpc :RetrieveAccessToken, User, AccessToken
    end

    Stub = Service.rpc_stub_class
  end
end
