# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authentication.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "GrpcClientAuthentication.AccessToken" do
    optional :token, :string, 1
  end
  add_message "GrpcClientAuthentication.User" do
    optional :id, :int64, 1
    optional :tenant, :string, 2
    optional :isCustomer, :string, 3
  end
end

module GrpcClientAuthentication
  AccessToken = Google::Protobuf::DescriptorPool.generated_pool.lookup("GrpcClientAuthentication.AccessToken").msgclass
  User = Google::Protobuf::DescriptorPool.generated_pool.lookup("GrpcClientAuthentication.User").msgclass
end
