# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent-platform/email.proto

require 'google/protobuf'

require 'model/user_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("agent-platform/email.proto", :syntax => :proto3) do
    add_message "Agent.SendEmailRequest" do
      optional :user, :message, 1, "Model.User"
      optional :unreadMessageCount, :int64, 2
      optional :tenant, :string, 3
    end
    add_message "Agent.SendEmailResponse" do
      optional :success, :bool, 1
    end
  end
end

module Agent
  SendEmailRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Agent.SendEmailRequest").msgclass
  SendEmailResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Agent.SendEmailResponse").msgclass
end
