# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: agent-platform/email.proto for package 'Agent'

require 'grpc'
require 'agent-platform/email_pb'

module Agent
  module Email
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'Agent.Email'

      rpc :SendEmail, ::Agent::SendEmailRequest, ::Agent::SendEmailResponse
    end

    Stub = Service.rpc_stub_class
  end
end
