# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: agent-platform/tenantSettings.proto for package 'Agent'

require 'grpc'
require 'agent-platform/tenantSettings_pb'

module Agent
  module TenantSettings
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'Agent.TenantSettings'

      rpc :RetrieveTenantSettings, ::Agent::RetrieveTenantSettingsRequest, ::Agent::RetrieveTenantSettingsResponse
    end

    Stub = Service.rpc_stub_class
  end
end
