# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent-platform/userPreferences.proto

require 'google/protobuf'

require 'model/user_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("agent-platform/userPreferences.proto", :syntax => :proto3) do
    add_message "Agent.ChatPreferences" do
      optional :notificationEscalationDelayInSeconds, :int64, 1
      optional :notificationEscalationEnabled, :bool, 2
    end
  end
end

module Agent
  ChatPreferences = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Agent.ChatPreferences").msgclass
end
